{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "d371a443-eb14-4074-adad-33eacb814d53",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "def promedios(vals):\n",
    "    \"\"\"\n",
    "    Calcula el promedio de una lista de números.\n",
    "    Verifica y elimina NaNs en los datos.\n",
    "\n",
    "    Parametros\n",
    "    ---------\n",
    "    vals: lista\n",
    "         lista con los numeros a promediar.\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    promedio: float\n",
    "          el promedio de los numeros (sin NaNs).\n",
    "    \"\"\"\n",
    "    num = [x for x in vals if isinstance(x, (int,float)) and not math.isnan(x)]\n",
    "    if not num:\n",
    "        return float('nan')\n",
    "    promedio =  sum(num) / len(num)\n",
    "    return promedio\n",
    "\n",
    "def mediana(vals):\n",
    "    \"\"\"\n",
    "    Calcula la mediana de una lista de números.\n",
    "    Ordena los datos y encuentra el valor central.\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    mediana : float\n",
    "           el valor central de la distribución\n",
    "    \"\"\"\n",
    "    num = sorted([x for x in vals if isinstance(x, (int,float)) and not math.isnan(x)])\n",
    "    n = len(num)\n",
    "    if n == 0:\n",
    "        return float('nan')\n",
    "        \n",
    "    mitad = n// 2\n",
    "    if n % 2== 0:\n",
    "        return (num [mitad -1] + num[mitad]) / 2\n",
    "    else:\n",
    "        return num[mitad]\n",
    "\n",
    "\n",
    "\n",
    "def varianza(vals):\n",
    "    \"\"\"\n",
    "    Calcula la varianza poblacional de una lista de números.\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals: lista\n",
    "          lista con los número.\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    varianza: float\n",
    "        la medida de dispersión respecto al promedio.\n",
    "    \n",
    "    \"\"\"\n",
    "    mu = promedios(vals)\n",
    "    num = [x for x in vals if isinstance(x, (int,float)) and not math.isnan(x)]\n",
    "    if not num:\n",
    "        return float('nan')\n",
    "\n",
    "    suma_cuadrados = sum((x - mu)**2 for x in num)\n",
    "    return suma_cuadrados / len(num)\n",
    "\n",
    "\n",
    "\n",
    "def desviacion_estandar(vals):\n",
    "    \"\"\"\n",
    "    Calcula la desviación estándar poblacional (STD)\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals: lista\n",
    "       lista con los números\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    std : float\n",
    "       la raíz cuadrada de la varianza\n",
    "    \"\"\"\n",
    "    var = varianza (vals)\n",
    "    return math.sqrt(var) if not math.isnan(var) else float('nan')\n",
    "\n",
    "\n",
    "\n",
    "def moda(lista):\n",
    "    \"\"\"\n",
    "    Estima la moda de una lista de datos (numéricos o categóricos).\n",
    "    Útil para tipos de galaxias.\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    lista: lista\n",
    "        lista con los datos a analizar.\n",
    "\n",
    "    Retorna \n",
    "    -------\n",
    "    moda: objeto\n",
    "       el valor que más se repite.\n",
    "    \"\"\"\n",
    "    if not lista:\n",
    "        return None\n",
    "\n",
    "    conteo = {}\n",
    "    for item in lista:\n",
    "        conteo[item] = conteo.get(item, 0 ) +1\n",
    "\n",
    "    max_frecuencia = max(conteo.values())\n",
    "    modas = [k for k, v in conteo.items() if v == max_frecuencia]\n",
    "\n",
    "    return modas[0] if len(modas) == 1 else modas\n",
    "\n",
    "\n",
    "\n",
    "def percentil (vals, p):\n",
    "    \"\"\"\n",
    "    Calcula un percentil específico de una muestra\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals : lista\n",
    "        lista con los números\n",
    "    p : float\n",
    "       el valor por debajo del cual cae p% de los datos\n",
    "       \n",
    "    Retorna\n",
    "    -------\n",
    "    valor: float\n",
    "         el valor por debajo del cual cae el p% de los datos.\n",
    "    \"\"\"\n",
    "    num = sorted([x for x in vals if isinstance(x, (int,float)) and not math.isnan(x)])\n",
    "    if not num:\n",
    "        return float('nan')\n",
    "\n",
    "    n = len(num)\n",
    "    pos = (n - 1) * (p/100)\n",
    "    idx_bajo = int(math.floor(pos))\n",
    "    idx_alto = int(math.ceil(pos))\n",
    "\n",
    "    if idx_bajo == idx_alto:\n",
    "        return num[idx_bajo]\n",
    "\n",
    "\n",
    "    d0 = num[idx_bajo] * (idx_alto - pos)\n",
    "    d1 = num[idx_alto] * (pos - idx_bajo)\n",
    "    return d0 + d1\n",
    "\n",
    "\n",
    "def rango(vals):\n",
    "    \"\"\"\n",
    "    Calcula el rango de una lista de números.\n",
    "    Es la diferencia entre el valor máximo y el valor mínimo.\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals: lista\n",
    "         lista con los números.\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    rango: float \n",
    "        la diferencia entre el máximo y el mínimo (excluyendo NaNs).\n",
    "    \"\"\"\n",
    "    num = [x for x in vals if isinstance(x, (int, float)) and not math.isnan(x)]\n",
    "    if not num :\n",
    "        return float('nan')\n",
    "    return max(num) - min(num)\n",
    "\n",
    "def rango_intercuartil(vals):\n",
    "    \"\"\"\n",
    "    Calculla el IQR (Q3 - Q1)\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals: lista\n",
    "        lista con los números.\n",
    "\n",
    "    Retorna \n",
    "    -------\n",
    "    iqr : float\n",
    "        el rango intercuartílico\n",
    "    \"\"\"\n",
    "    q1 = percentil(vals, 25)\n",
    "    q3 = percentil (vals, 75)\n",
    "    return q3 - q1\n",
    "\n",
    "def mad(vals):\n",
    "    \"\"\"\n",
    "    Calcula la Desviación Absoluta Mediana (MAD)\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals: lista\n",
    "       lista con los números.\n",
    "\n",
    "    Retorna \n",
    "    ------\n",
    "    mad: float \n",
    "        la mediana de las desviaciones absolutas respecto a la mediana\n",
    "    \"\"\"\n",
    "    med = mediana(vals)\n",
    "    desviaciones = [abs(x - med) for x in vals if isinstance(x, (int, float)) and not math.isnan(x)]\n",
    "    return mediana(desviaciones)\n",
    "\n",
    "\n",
    "\n",
    "def covarianza (vals_x, vals_y):\n",
    "    \"\"\"\n",
    "    Calcula la covarianza entre dos conjuntos de datos.\n",
    "\n",
    "    Paramteros\n",
    "    -------\n",
    "    vals_x, vals_y: listas\n",
    "        lista de igual longitud con los datos\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    cov: float\n",
    "      la covarianza de las variables.\n",
    "    \"\"\"\n",
    "\n",
    "    x_num = []\n",
    "    y_num = []\n",
    "\n",
    "    num = min(len(vals_x), len(vals_y))\n",
    "    for i in range(len(vals_):\n",
    "        if math.isfinite(vals_x[i]) and math.isfinite(vals_y[i]):\n",
    "            x_num.append(vals_x[i])\n",
    "            y_num.append(vals_y[i])\n",
    "\n",
    "    if not x_num:\n",
    "        return float('nan')\n",
    "\n",
    "    mu_x = promedio(x_num)\n",
    "    mu_y = promedio(y_num)\n",
    "\n",
    "    suma = sum((xi - mu_x) * (yi- mu_y) for xi, yi in zip(x_num, y_num))\n",
    "    return suma / len(x_num)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def correlacion(vals_x, vals_y):\n",
    "    \"\"\"\n",
    "    Calcula el coeficiente de correlación\n",
    "\n",
    "    Parametros\n",
    "    -------\n",
    "    vals_x, vals_y: listas\n",
    "        lista con los datos\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    r : float\n",
    "       coeficiente de correlación entre -1 y 1\n",
    "    \"\"\"\n",
    "    cov = covarianza(vals_x, vals_y)\n",
    "    std_x = desviacion_estandar(vals_x)\n",
    "    std_y = desviacion_estandar(vals_y)\n",
    "\n",
    "    if math.isnan(cov) or std_x == 0 or std_y == 0:\n",
    "        return float('nan')\n",
    "    return cov/ (std_x * std_y)\n",
    "        \n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "11bb7362-b673-478b-bcac-a2ae1743083b",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
